name: Deploy to Google Cloud Platform
on:
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCLOUD_AUTH }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA

      # Deploy Docker image to Cloud Run
      - name: Deploy to CLoud Run
        run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA --platform managed --region $RUN_REGION

      # Deploy to App Engine flexible
      - name: Deploy to App Engine
        run: gcloud beta app deploy

